### ISSUE TITLE
./crawlab api  报错

### ISSUE THREAD

**Issue by pierolaugh** [crawlab-team/crawlab#1046]
xxx backend % ./crawlab api
Using config file: /Users/xxx/Data/Deeptech/crawlab/backend/conf/config.yml
[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:   export GIN_MODE=release
 - using code:  gin.SetMode(gin.ReleaseMode)

spider error: forbidden
/Users/xxx/go/pkg/mod/github.com/crawlab-team/go-trace@v0.1.1/trace.go:13 github.com/crawlab-team/go-trace.TraceError()
/Users/xxx/go/pkg/mod/github.com/crawlab-team/crawlab-core@v0.6.0-beta.20211224.1718/spider/admin/service.go:192 github.com/crawlab-team/crawlab-core/spider/admin.NewSpiderAdminService()
/usr/local/go/src/reflect/value.go:543 reflect.Value.call()
/usr/local/go/src/reflect/value.go:339 reflect.Value.Call()
/Users/xxx/go/pkg/mod/go.uber.org/dig@v1.10.0/dig.go:284 go.uber.org/dig.defaultInvoker()
/Users/xxx/go/pkg/mod/go.uber.org/dig@v1.10.0/dig.go:710 go.uber.org/dig.(*node).Call()
/Users/xxx/go/pkg/mod/go.uber.org/dig@v1.10.0/param.go:245 go.uber.org/dig.paramSingle.Build()
/Users/xxx/go/pkg/mod/go.uber.org/dig@v1.10.0/param.go:201 go.uber.org/dig.paramList.BuildList()
/Users/xxx/go/pkg/mod/go.uber.org/dig@v1.10.0/dig.go:432 go.uber.org/dig.(*Container).Invoke()
/Users/xxx/go/pkg/mod/github.com/crawlab-team/crawlab-core@v0.6.0-beta.20211224.1718/controllers/spider.go:1104 github.com/crawlab-team/crawlab-core/controllers.newSpiderContext()
/Users/xxx/go/pkg/mod/github.com/crawlab-team/crawlab-core@v0.6.0-beta.20211224.1718/controllers/spider.go:38 github.com/crawlab-team/crawlab-core/controllers.getSpiderActions()
/Users/xxx/go/pkg/mod/github.com/crawlab-team/crawlab-core@v0.6.0-beta.20211224.1718/controllers/spider.go:1125 github.com/crawlab-team/crawlab-core/controllers.newSpiderController()
/Users/xxx/go/pkg/mod/github.com/crawlab-team/crawlab-core@v0.6.0-beta.20211224.1718/controllers/init.go:16 github.com/crawlab-team/crawlab-core/controllers.InitControllers()
/Users/xxx/Data/Deeptech/crawlab/backend/apps/utils.go:26 crawlab/apps.initModule()
/Users/xxx/Data/Deeptech/crawlab/backend/apps/api.go:28 crawlab/apps.(*Api).Init()
/Users/xxx/Data/Deeptech/crawlab/backend/apps/api.go:77 crawlab/apps.NewApi()
/Users/xxx/Data/Deeptech/crawlab/backend/cmd/api.go:18 crawlab/cmd.glob..func1()
/Users/xxx/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:856 github.com/spf13/cobra.(*Command).execute()
/Users/xxx/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 github.com/spf13/cobra.(*Command).ExecuteC()
/Users/xxx/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897 github.com/spf13/cobra.(*Command).Execute()
/Users/xxx/Data/Deeptech/crawlab/backend/cmd/root.go:28 crawlab/cmd.Execute()
/Users/xxx/Data/Deeptech/crawlab/backend/main.go:8 main.main()
/usr/local/go/src/runtime/proc.go:255 runtime.main()
/usr/local/go/src/runtime/asm_arm64.s:1133 runtime.goexit()
panic: could not build arguments for function "github.com/crawlab-team/crawlab-core/controllers".newSpiderContext.func1 (/Users/xxx/go/pkg/mod/github.com/crawlab-team/crawlab-core@v0.6.0-beta.20211224.1718/controllers/spider.go:1104): failed to build interfaces.SpiderAdminService: received non-nil error from function "github.com/crawlab-team/crawlab-core/spider/admin".NewSpiderAdminService (/Users/xxx/go/pkg/mod/github.com/crawlab-team/crawlab-core@v0.6.0-beta.20211224.1718/spider/admin/service.go:161): spider error: forbidden

goroutine 1 [running]:
github.com/crawlab-team/crawlab-core/controllers.newSpiderContext()
        /Users/xxx/go/pkg/mod/github.com/crawlab-team/crawlab-core@v0.6.0-beta.20211224.1718/controllers/spider.go:1113 +0x23c
github.com/crawlab-team/crawlab-core/controllers.getSpiderActions()
        /Users/xxx/go/pkg/mod/github.com/crawlab-team/crawlab-core@v0.6.0-beta.20211224.1718/controllers/spider.go:38 +0x20
github.com/crawlab-team/crawlab-core/controllers.newSpiderController()
        /Users/xxx/go/pkg/mod/github.com/crawlab-team/crawlab-core@v0.6.0-beta.20211224.1718/controllers/spider.go:1125 +0x20
github.com/crawlab-team/crawlab-core/controllers.InitControllers()
        /Users/xxx/go/pkg/mod/github.com/crawlab-team/crawlab-core@v0.6.0-beta.20211224.1718/controllers/init.go:16 +0xd8
crawlab/apps.initModule({0x1034c6727, 0xb}, 0x103929a68)
        /Users/xxx/Data/Deeptech/crawlab/backend/apps/utils.go:26 +0x28
crawlab/apps.(*Api).Init(0x14000399ca0)
        /Users/xxx/Data/Deeptech/crawlab/backend/apps/api.go:28 +0x40
crawlab/apps.NewApi()
        /Users/xxx/Data/Deeptech/crawlab/backend/apps/api.go:77 +0x84
crawlab/cmd.glob..func1(0x104093880, {0x1040d54d8, 0x0, 0x0})
        /Users/xxx/Data/Deeptech/crawlab/backend/cmd/api.go:18 +0x20
github.com/spf13/cobra.(*Command).execute(0x104093880, {0x1040d54d8, 0x0, 0x0})
        /Users/xxx/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:856 +0x640
github.com/spf13/cobra.(*Command).ExecuteC(0x104094000)
        /Users/xxx/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x404
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/xxx/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
crawlab/cmd.Execute(...)
        /Users/xxx/Data/Deeptech/crawlab/backend/cmd/root.go:28
main.main()
        /Users/xxx/Data/Deeptech/crawlab/backend/main.go:8 +0x30

**Comment by tikazyq** [comment]
```bash
export CRAWLAB_NODE_SERVER=Y
go run main.go master
```

**Comment by tikazyq** [comment]
duplicated in https://github.com/crawlab-team/crawlab/issues/1039

**Comment by stevecheen** [comment]
try:
linux: export CRAWLAR_NODE_MASTER=Y
window $env:CRAWLAR_NODE_MASTER="Y"
