### ISSUE TITLE
loginerror TypeError: Cannot read properties of undefined (reading 'data')

### ISSUE THREAD

**Issue by z1220726337** [crawlab-team/crawlab#1056]
**Bug 描述**
账密登录报错内容：
TypeError: Cannot read properties of undefined (reading 'data')

**复现步骤**
该 Bug 复现步骤如下，使用教程docker安装最新0.6版本
git clone https://github.com/crawlab-team/examples
cd examples/docker/basic
docker-compose up -d
2. 登录输入默认admin账密报错

**Comment by z1220726337** [comment]
补充一下log，好像是mongo的问题

- crawlab_example_mongo log

WARNING: MongoDB 5.0+ requires a CPU with AVX support, and your current system does not appear to have that!
  see https://jira.mongodb.org/browse/SERVER-54407
  see also https://www.mongodb.com/community/forums/t/mongodb-5-0-cpu-intel-g4650-compatibility/116610/2
  see also https://github.com/docker-library/mongo/issues/485#issuecomment-891991814


WARNING: MongoDB 5.0+ requires a CPU with AVX support, and your current system does not appear to have that!
  see https://jira.mongodb.org/browse/SERVER-54407
  see also https://www.mongodb.com/community/forums/t/mongodb-5-0-cpu-intel-g4650-compatibility/116610/2
  see also https://github.com/docker-library/mongo/issues/485#issuecomment-891991814


WARNING: MongoDB 5.0+ requires a CPU with AVX support, and your current system does not appear to have that!
  see https://jira.mongodb.org/browse/SERVER-54407
  see also https://www.mongodb.com/community/forums/t/mongodb-5-0-cpu-intel-g4650-compatibility/116610/2
  see also https://github.com/docker-library/mongo/issues/485#issuecomment-891991814

- crawlab_example_worker02 log

/go/pkg/mod/github.com/crawlab-team/go-trace@v0.1.1/trace.go:13 github.com/crawlab-team/go-trace.TraceError()
/go/pkg/mod/github.com/crawlab-team/crawlab-core@v0.6.0-beta.20211230.1200/grpc/client/client.go:268 github.com/crawlab-team/crawlab-core/grpc/client.(*Client)._connect()
/go/pkg/mod/github.com/cenkalti/backoff/v4@v4.1.0/retry.go:55 github.com/cenkalti/backoff/v4.RetryNotifyWithTimer()
/go/pkg/mod/github.com/cenkalti/backoff/v4@v4.1.0/retry.go:34 github.com/cenkalti/backoff/v4.RetryNotify()
/go/pkg/mod/github.com/crawlab-team/crawlab-core@v0.6.0-beta.20211230.1200/grpc/client/client.go:248 github.com/crawlab-team/crawlab-core/grpc/client.(*Client).connect()
/go/pkg/mod/github.com/crawlab-team/crawlab-core@v0.6.0-beta.20211230.1200/grpc/client/client.go:61 github.com/crawlab-team/crawlab-core/grpc/client.(*Client).Start()
/go/pkg/mod/github.com/crawlab-team/crawlab-core@v0.6.0-beta.20211230.1200/node/service/worker_service.go:45 github.com/crawlab-team/crawlab-core/node/service.(*WorkerService).Start()
/usr/local/go/src/runtime/asm_amd64.s:1371 runtime.goexit()
grpc error: client failed to start
/go/pkg/mod/github.com/crawlab-team/go-trace@v0.1.1/trace.go:6 github.com/crawlab-team/go-trace.PrintError()
/go/pkg/mod/github.com/crawlab-team/crawlab-core@v0.6.0-beta.20211230.1200/utils/backoff.go:13 github.com/crawlab-team/crawlab-core/utils.BackoffErrorNotify.func1()
/go/pkg/mod/github.com/cenkalti/backoff/v4@v4.1.0/retry.go:69 github.com/cenkalti/backoff/v4.RetryNotifyWithTimer()
/go/pkg/mod/github.com/cenkalti/backoff/v4@v4.1.0/retry.go:34 github.com/cenkalti/backoff/v4.RetryNotify()
/go/pkg/mod/github.com/crawlab-team/crawlab-core@v0.6.0-beta.20211230.1200/grpc/client/client.go:248 github.com/crawlab-team/crawlab-core/grpc/client.(*Client).connect()
/go/pkg/mod/github.com/crawlab-team/crawlab-core@v0.6.0-beta.20211230.1200/grpc/client/client.go:61 github.com/crawlab-team/crawlab-core/grpc/client.(*Client).Start()
/go/pkg/mod/github.com/crawlab-team/crawlab-core@v0.6.0-beta.20211230.1200/node/service/worker_service.go:45 github.com/crawlab-team/crawlab-core/node/service.(*WorkerService).Start()
/usr/local/go/src/runtime/asm_amd64.s:1371 runtime.goexit()
2022/01/11 17:40:16 error grpc client connect error: grpc error: client failed to start. reattempt in 42.2 seconds...

- crawlab_example_worker01 log

/go/pkg/mod/github.com/crawlab-team/go-trace@v0.1.1/trace.go:13 github.com/crawlab-team/go-trace.TraceError()
/go/pkg/mod/github.com/crawlab-team/crawlab-core@v0.6.0-beta.20211230.1200/grpc/client/client.go:268 github.com/crawlab-team/crawlab-core/grpc/client.(*Client)._connect()
/go/pkg/mod/github.com/cenkalti/backoff/v4@v4.1.0/retry.go:55 github.com/cenkalti/backoff/v4.RetryNotifyWithTimer()
/go/pkg/mod/github.com/cenkalti/backoff/v4@v4.1.0/retry.go:34 github.com/cenkalti/backoff/v4.RetryNotify()
/go/pkg/mod/github.com/crawlab-team/crawlab-core@v0.6.0-beta.20211230.1200/grpc/client/client.go:248 github.com/crawlab-team/crawlab-core/grpc/client.(*Client).connect()
/go/pkg/mod/github.com/crawlab-team/crawlab-core@v0.6.0-beta.20211230.1200/grpc/client/client.go:61 github.com/crawlab-team/crawlab-core/grpc/client.(*Client).Start()
/go/pkg/mod/github.com/crawlab-team/crawlab-core@v0.6.0-beta.20211230.1200/node/service/worker_service.go:45 github.com/crawlab-team/crawlab-core/node/service.(*WorkerService).Start()
/usr/local/go/src/runtime/asm_amd64.s:1371 runtime.goexit()
grpc error: client failed to start
/go/pkg/mod/github.com/crawlab-team/go-trace@v0.1.1/trace.go:6 github.com/crawlab-team/go-trace.PrintError()
/go/pkg/mod/github.com/crawlab-team/crawlab-core@v0.6.0-beta.20211230.1200/utils/backoff.go:13 github.com/crawlab-team/crawlab-core/utils.BackoffErrorNotify.func1()
/go/pkg/mod/github.com/cenkalti/backoff/v4@v4.1.0/retry.go:69 github.com/cenkalti/backoff/v4.RetryNotifyWithTimer()
/go/pkg/mod/github.com/cenkalti/backoff/v4@v4.1.0/retry.go:34 github.com/cenkalti/backoff/v4.RetryNotify()
/go/pkg/mod/github.com/crawlab-team/crawlab-core@v0.6.0-beta.20211230.1200/grpc/client/client.go:248 github.com/crawlab-team/crawlab-core/grpc/client.(*Client).connect()
/go/pkg/mod/github.com/crawlab-team/crawlab-core@v0.6.0-beta.20211230.1200/grpc/client/client.go:61 github.com/crawlab-team/crawlab-core/grpc/client.(*Client).Start()
/go/pkg/mod/github.com/crawlab-team/crawlab-core@v0.6.0-beta.20211230.1200/node/service/worker_service.go:45 github.com/crawlab-team/crawlab-core/node/service.(*WorkerService).Start()
/usr/local/go/src/runtime/asm_amd64.s:1371 runtime.goexit()
2022/01/11 17:41:08 error grpc client connect error: grpc error: client failed to start. reattempt in 51.7 seconds...
context deadline exceeded
/go/pkg/mod/github.com/crawlab-team/go-trace@v0.1.1/trace.go:13 github.com/crawlab-team/go-trace.TraceError()
/go/pkg/mod/github.com/crawlab-team/crawlab-core@v0.6.0-beta.20211230.1200/grpc/client/client.go:268 github.com/crawlab-team/crawlab-core/grpc/client.(*Client)._connect()
/go/pkg/mod/github.com/cenkalti/backoff/v4@v4.1.0/retry.go:55 github.com/cenkalti/backoff/v4.RetryNotifyWithTimer()
/go/pkg/mod/github.com/cenkalti/backoff/v4@v4.1.0/retry.go:34 github.com/cenkalti/backoff/v4.RetryNotify()
/go/pkg/mod/github.com/crawlab-team/crawlab-core@v0.6.0-beta.20211230.1200/grpc/client/client.go:248 github.com/crawlab-team/crawlab-core/grpc/client.(*Client).connect()
/go/pkg/mod/github.com/crawlab-team/crawlab-core@v0.6.0-beta.20211230.1200/grpc/client/client.go:61 github.com/crawlab-team/crawlab-core/grpc/client.(*Client).Start()
/go/pkg/mod/github.com/crawlab-team/crawlab-core@v0.6.0-beta.20211230.1200/node/service/worker_service.go:45 github.com/crawlab-team/crawlab-core/node/service.(*WorkerService).Start()
/usr/local/go/src/runtime/asm_amd64.s:1371 runtime.goexit()
panic: grpc error: client failed to start

goroutine 13 [running]:
github.com/crawlab-team/crawlab-core/node/service.(*WorkerService).Start(0xc0000eb830)
        /go/pkg/mod/github.com/crawlab-team/crawlab-core@v0.6.0-beta.20211230.1200/node/service/worker_service.go:46 +0x1c6
created by crawlab/apps.(*Worker).Start
        /go/src/app/apps/worker.go:30 +0x46

**Comment by z1220726337** [comment]
![e3e19f1177e718e573ce3eb8bbeb3ff](https://user-images.githubusercontent.com/39333590/148920657-94afdfcc-7d7a-4f57-b3b0-aa323f3552a8.png)

**Comment by z1220726337** [comment]
解决了，是mongo版本过高引起的，推荐安装mogo4.4.6
修改docker-compose.yml中
image: mongo:latest  为  image: mongo:4.4.6
