### ISSUE TITLE
集成scrapy的pipeline时，运行save_item时候报错

### ISSUE THREAD

**Issue by jjzhoujun** [crawlab-team/crawlab#1130]
**Bug 描述**
例如，当用v0.6版本集成scrapy的save_item到pipeline时候，运行报错

**复现步骤**
该 Bug 复现步骤如下
1. scrapy新项目，settings的ITEM_PIPELINES里加入 'crawlab.scrapy.pipelines.CrawlabPipeline': 888
2. 运行项目，之前OK的项目，报如下错误：
 'scrapy.spidermiddlewares.depth.DepthMiddleware']
2022-06-19 19:29:29 [twisted] CRITICAL: Unhandled error in Deferred:
2022-06-19 19:29:29 [twisted] CRITICAL:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 1660, in _inlineCallbacks
    result = current_context.run(gen.send, result)
  File "/usr/local/lib/python3.7/site-packages/scrapy/crawler.py", line 87, in crawl
    self.engine = self._create_engine()
  File "/usr/local/lib/python3.7/site-packages/scrapy/crawler.py", line 101, in _create_engine
    return ExecutionEngine(self, lambda _: self.stop())
  File "/usr/local/lib/python3.7/site-packages/scrapy/core/engine.py", line 70, in __init__
    self.scraper = Scraper(crawler)
  File "/usr/local/lib/python3.7/site-packages/scrapy/core/scraper.py", line 71, in __init__
    self.itemproc = itemproc_cls.from_crawler(crawler)
  File "/usr/local/lib/python3.7/site-packages/scrapy/middleware.py", line 53, in from_crawler
    return cls.from_settings(crawler.settings, crawler)
  File "/usr/local/lib/python3.7/site-packages/scrapy/middleware.py", line 34, in from_settings
    mwcls = load_object(clspath)
  File "/usr/local/lib/python3.7/site-packages/scrapy/utils/misc.py", line 61, in load_object
    mod = import_module(module)
  File "/usr/lib64/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'crawlab.scrapy'

之前是报 crawlab 找不到，单独用 pip install crawlab 后，就报上述错误了，想用pip安装不了。
[root@cecloud-ecs-78456 62adaf0b2fc909326db774e7]# pip install crawlab.scrapy
ERROR: Could not find a version that satisfies the requirement crawlab.scrapy (from versions: none)
ERROR: No matching distribution found for crawlab.scrapy

**期望结果**
能正常存入mongodb，不报错能工作。

**截屏**
CPU是ARM64的，对应的软件环境，Scrapy的版本不是默认v0.6的版本，因为高版本之前运行会报一个Reactor的错误，就降低到2.5.1了。
![image](https://user-images.githubusercontent.com/5793642/174479068-4c7c63e6-a553-4ec8-a6a2-068f09df22eb.png)

**Comment by tikazyq** [comment]
crawlab-sdk 版本多少？

`pip freeze | grep crawlab-sdk`
