### ISSUE TITLE
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: crashed.

### ISSUE THREAD

**Issue by ma-pony** [crawlab-team/crawlab#1178]
**Describe the bug**
按照官方文档安装crawlab后，运行selenium爬虫Chrome crashed.

**To Reproduce**
1. 通过docker-compose安装crawlab
```
version: '3.3'
services:
  master:
    image: crawlabteam/crawlab
    container_name: crawlab_master
    environment:
      CRAWLAB_NODE_MASTER: "Y"
      CRAWLAB_MONGO_HOST: "mongo"
    ports:
      - "8080:8080"
    depends_on:
      - mongo
  mongo:
    image: mongo:4.2
```
2.  创建新的爬虫项目
3. 新建main.py文件，填入代码
代码取自crawlab-demo项目
https://github.com/crawlab-team/crawlab-demo/blob/main/crawlab_demo/data/spiders/python/selenium_36kr/main.py#L2
```
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By

# create web driver with chrome
chrome_options = Options()
chrome_options.add_argument('--headless')
chrome_options.add_argument('--no-sandbox')
chrome_options.add_argument('--disable-dev-shm-usage')
browser = webdriver.Chrome(options=chrome_options)


# navigate to news list page
browser.get('https://36kr.com/information/web_news/')

# get article items
items = browser.find_elements(by=By.CSS_SELECTOR, value='.information-flow-list > .information-flow-item')

# iterate items
for item in items:
    # fields
    el_title = item.find_element(by=By.CSS_SELECTOR, value='.article-item-title')
    title = el_title.text
    url = el_title.get_attribute('href')
    topic = item.find_element(by=By.CSS_SELECTOR, value='.kr-flow-bar-motif > a').text
    description = item.find_element(by=By.CSS_SELECTOR, value='.article-item-description').text
    try:
        pic_url = item.find_element(by=By.CSS_SELECTOR, value='.article-item-pic > img').get_attribute('src')
    except:
        pic_url = None

    # save to crawlab
    print({
        'title': title,
        'url': url,
        'topic': topic,
        'description': description,
        'pic_url': pic_url,
    })
```
4. 运行爬虫，报错Chrome failed to start: crashed.
```
Traceback (most recent call last):
  File "main.py", line 10, in <module>
    browser = webdriver.Chrome(options=chrome_options)
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/chrome/webdriver.py", line 70, in __init__
    super(WebDriver, self).__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/chromium/webdriver.py", line 92, in __init__
    RemoteWebDriver.__init__(
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py", line 275, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py", line 365, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py", line 430, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: crashed.
  (chrome not reachable)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Stacktrace:
#0 0x0040005adcd3 <unknown>
#1 0x0040003b5968 <unknown>
#2 0x0040003da25c <unknown>
#3 0x0040003d58fa <unknown>
#4 0x00400041094a <unknown>
#5 0x00400040aaa3 <unknown>
#6 0x0040003e03fa <unknown>
#7 0x0040003e1555 <unknown>
#8 0x0040005f52bd <unknown>
#9 0x0040005f9418 <unknown>
#10 0x0040005df36e <unknown>
#11 0x0040005fa078 <unknown>
#12 0x0040005d3bb0 <unknown>
#13 0x004000616d58 <unknown>
#14 0x004000616ed8 <unknown>
#15 0x004000630cfd <unknown>
#16 0x00400244b609 <unknown>


```

**Expected behavior**
期望正常运行
**Screenshots**
![image](https://user-images.githubusercontent.com/38464007/187382913-66fb1e97-529f-4804-948f-9cd2a97ac1ae.png)

**Comment by tikazyq** [comment]
unable to reproduce in the current version

<img width="1378" alt="image" src="https://user-images.githubusercontent.com/3393101/193052667-b3edda10-04cd-4f8b-824f-af3730f7bb3c.png">

<img width="1049" alt="image" src="https://user-images.githubusercontent.com/3393101/193053067-a0b0186c-8ccd-422a-97df-1885956bf84b.png">

**Comment by flyz1** [comment]
您好，请问您问题解决了吗？

**Comment by ma-pony** [comment]
> 您好，请问您问题解决了吗？

最新版的已经没问题了

**Comment by SimithXu** [comment]
<img width="1506" alt="image" src="https://github.com/user-attachments/assets/4816ede7-7483-4f5e-a330-ba785a010032">
我在0.6.3版本遇到了类似的问题，就是驱动版本和浏览器版本匹配不上，导致无法进行驱动

**Comment by ma-pony** [comment]
> <img alt="image" width="1506" src="https://private-user-images.githubusercontent.com/39891052/386573113-4816ede7-7483-4f5e-a330-ba785a010032.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIyNjU1ODIsIm5iZiI6MTczMjI2NTI4MiwicGF0aCI6Ii8zOTg5MTA1Mi8zODY1NzMxMTMtNDgxNmVkZTctNzQ4My00ZjVlLWEzMzAtYmE3ODVhMDEwMDMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIyVDA4NDgwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVlZDY5ODAzOGQ2YWJiNGVhMDczMmQzOTc0NmVhZjFiNTMyYjY2MzNiYjhmMmEyMjQzY2ZlMWQ2YTBiNWE5MWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.s0hnybnm73XMdnHaNNYFzB7IZPTsEJ30Hiw3qnVtMOY"> 我在0.6.3版本遇到了类似的问题，就是驱动版本和浏览器版本匹配不上，导致无法进行驱动

根据你的驱动版本，重装一个浏览器应该就好了吧
