### ISSUE TITLE
container crash (Panic)

### ISSUE THREAD

**Issue by saleh-hom** [crawlab-team/crawlab#1444]
I am using Crawlab pro is a stack deployed on a docker swarm, all features are working fine. I am also using 1 worker node on a different machine.
However every few days the master node panics with the below error messages.

panic: runtime error: index out of range [104] with length 62
goroutine 15940761 [running]:
github.com/emirpasic/gods/lists/arraylist.(*List).Add(...)
	/go/pkg/mod/github.com/emirpasic/gods@v1.18.1/lists/arraylist/arraylist.go:47
github.com/crawlab-team/crawlab-pro/core/metric.(*Service).getAllNodeMetrics.func1.1({0xc000dcc000?, 0xd4, 0xc0010ec2b0?})
	/go/src/app/core/metric/service.go:226 +0x22d
github.com/crawlab-team/crawlab-pro/core/metric.(*Service).requestRemoteNodeMetrics(0xc000024480, {0x229d490, 0xc001c37860}, {0x22aa028, 0xc000af5930}, 0x1985063?, 0xc001990ee8)
	/go/src/app/core/metric/service.go:334 +0x4da
github.com/crawlab-team/crawlab-pro/core/metric.(*Service).getAllNodeMetrics.func1({{0x65, 0xa7, 0xc1, 0xbd, 0xdc, 0x6e, 0x24, 0xde, 0x5b, 0x5a, ...}, ...})
	/go/src/app/core/metric/service.go:224 +0xfa
created by github.com/crawlab-team/crawlab-pro/core/metric.(*Service).getAllNodeMetrics
	/go/src/app/core/metric/service.go:223 +0x40c

I don't think there are set of steps to reproduce the issue, simply leaving the stack running will eventually make the container panic

**Comment by oleksa-dev** [comment]
@saleh-hom hi, have the same [panic issue](https://github.com/crawlab-team/crawlab/issues/1391) `runtime error: index out of range` in pro version.
It appears randomly during requests to API performed my Crawlab frontend side.
