### ISSUE TITLE
按照文档中的配置好后启动docker容器无法访问

### ISSUE THREAD

**Issue by FENG1000** [crawlab-team/crawlab#200]
```
goroutine 1 [running]:
runtime/debug.Stack(0x0, 0x0, 0x0)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x9d
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
main.main()
	/go/src/app/main.go:33 +0x142
panic: no reachable servers

goroutine 1 [running]:
main.main()
	/go/src/app/main.go:34 +0x1cde
 * Starting nginx nginx
   ...done.
[GIN-debug] [WARNING] Creating an Engine instance with the Logger and Recovery middleware already attached.

[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:	export GIN_MODE=release
 - using code:	gin.SetMode(gin.ReleaseMode)

2019/09/02 02:18:30  info 初始化配置成功                  
2019/09/02 02:18:30  info 初始化日志设置成功                
goroutine 1 [running]:
runtime/debug.Stack(0x0, 0x0, 0x0)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x9d
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
main.main()
	/go/src/app/main.go:33 +0x142
panic: no reachable servers

goroutine 1 [running]:
main.main()
	/go/src/app/main.go:34 +0x1cde
```

**Comment by tikazyq** [comment]
`panic: no reachable servers`是指mongodb没有连接上，请再次检查mongodb的连接

**Comment by FENG1000** [comment]
> `panic: no reachable servers`是指mongodb没有连接上，请再次检查mongodb的连接

感谢，已解决
