### ISSUE TITLE
mongodb no reachable

### ISSUE THREAD

**Issue by guapier** [crawlab-team/crawlab#373]
请问一下那个mongodb no reachable servers 如何解决，这个问题在有的机器上不会出现，在有的机器上就会出现

master    | 2019/12/18 07:26:45  info 初始化配置成功                  
master    | 2019/12/18 07:26:45  info 初始化日志设置成功                
master    | 2019/12/18 07:26:45  info 初始化定期清理日志配置成功            
master    | 2019/12/18 07:26:45 error init mongodb error:no reachable servers
master    | goroutine 1 [running]:
master    | runtime/debug.Stack(0x0, 0x0, 0x0)
master    |  /usr/local/go/src/runtime/debug/stack.go:24 +0x9d
master    | runtime/debug.PrintStack()
master    |  /usr/local/go/src/runtime/debug/stack.go:16 +0x22
master    | main.main()
master    |  /go/src/app/main.go:55 +0x2b2
master    | panic: no reachable servers
master    | 
master    | goroutine 1 [running]:
master    | main.main()
master    |  /go/src/app/main.go:56 +0x25a7
worker exited with code 2

**Comment by kanadeblisst** [comment]
我的虚拟机上稳定出现，使用的是docker-compose， yml文件如下：
version: '3.3'
services:
  master: 
    image: tikazyq/crawlab:latest
    container_name: crawlab-master
    environment:
      CRAWLAB_API_ADDRESS: "http://localhost:8000"
      CRAWLAB_SERVER_MASTER: "Y"
      CRAWLAB_MONGO_HOST: "mongo"
      CRAWLAB_REDIS_ADDRESS: "redis"
    ports:    
      - "8080:8080" # frontend
      - "8000:8000" # backend
    depends_on:
      - mongo
      - redis
  worker:
    image: tikazyq/crawlab:latest
    container_name: crawlab-worker
    environment:
      CRAWLAB_SERVER_MASTER: "N"
      CRAWLAB_MONGO_HOST: "mongo"
      CRAWLAB_REDIS_ADDRESS: "redis"
    depends_on:
      - mongo
      - redis
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"

**Comment by tikazyq** [comment]
启动没有严格按照顺序执行导致的，参照这个文档修复，https://docs.docker.com/compose/startup-order/

**Comment by epirus** [comment]
这个问题好像没有解决 应该出错了

**Comment by kanadeblisst** [comment]
> 启动没有严格按照顺序执行导致的，参照这个文档修复，https://docs.docker.com/compose/startup-order/

我试着按照文档操作，但还是报同样的错误。而且根据启动日志显示，redis和mongo是在master前就已经初始化的，可能不是启动顺序导致的。完整日志如下：
```
crawlab-worker |  * Starting nginx nginx
mongo_1   | 2019-12-19T01:21:48.008+0000 I  CONTROL  [main] Automatically disabling TLS 1.0, to force-enable TLS 1.0 specify --sslDisabledProtocols 'none'
mongo_1   | 2019-12-19T01:21:48.012+0000 I  CONTROL  [initandlisten] MongoDB starting : pid=1 port=27017 dbpath=/data/db 64-bit host=7c16f1e2a410
mongo_1   | 2019-12-19T01:21:48.012+0000 I  CONTROL  [initandlisten] db version v4.2.2
mongo_1   | 2019-12-19T01:21:48.012+0000 I  CONTROL  [initandlisten] git version: a0bbbff6ada159e19298d37946ac8dc4b497eadf
mongo_1   | 2019-12-19T01:21:48.012+0000 I  CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.1.1  11 Sep 2018
mongo_1   | 2019-12-19T01:21:48.012+0000 I  CONTROL  [initandlisten] allocator: tcmalloc
mongo_1   | 2019-12-19T01:21:48.012+0000 I  CONTROL  [initandlisten] modules: none
mongo_1   | 2019-12-19T01:21:48.012+0000 I  CONTROL  [initandlisten] build environment:
mongo_1   | 2019-12-19T01:21:48.012+0000 I  CONTROL  [initandlisten]     distmod: ubuntu1804
mongo_1   | 2019-12-19T01:21:48.012+0000 I  CONTROL  [initandlisten]     distarch: x86_64
mongo_1   | 2019-12-19T01:21:48.012+0000 I  CONTROL  [initandlisten]     target_arch: x86_64
mongo_1   | 2019-12-19T01:21:48.012+0000 I  CONTROL  [initandlisten] options: { net: { bindIp: "*" } }
mongo_1   | 2019-12-19T01:21:48.012+0000 I  STORAGE  [initandlisten] Detected data files in /data/db created by the 'wiredTiger' storage engine, so setting the active storage engine to 'wiredTiger'.
mongo_1   | 2019-12-19T01:21:48.013+0000 I  STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=397M,cache_overflow=(file_max=0M),session_max=33000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000,close_scan_interval=10,close_handle_minimum=250),statistics_log=(wait=0),verbose=[recovery_progress,checkpoint_progress],
mongo_1   | 2019-12-19T01:21:48.928+0000 I  STORAGE  [initandlisten] WiredTiger message [1576718508:928844][1:0x7fa4b031fb00], txn-recover: Recovering log 2 through 3
mongo_1   | 2019-12-19T01:21:49.014+0000 I  STORAGE  [initandlisten] WiredTiger message [1576718509:14037][1:0x7fa4b031fb00], txn-recover: Recovering log 3 through 3
redis_1   | 1:C 19 Dec 2019 01:21:48.086 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis_1   | 1:C 19 Dec 2019 01:21:48.086 # Redis version=5.0.7, bits=64, commit=00000000, modified=0, pid=1, just started
redis_1   | 1:C 19 Dec 2019 01:21:48.086 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
redis_1   | 1:M 19 Dec 2019 01:21:48.086 * Running mode=standalone, port=6379.
redis_1   | 1:M 19 Dec 2019 01:21:48.087 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
redis_1   | 1:M 19 Dec 2019 01:21:48.087 # Server initialized
redis_1   | 1:M 19 Dec 2019 01:21:48.087 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
redis_1   | 1:M 19 Dec 2019 01:21:48.088 * Ready to accept connections
crawlab-master |  * Starting nginx nginx
mongo_1   | 2019-12-19T01:21:49.151+0000 I  STORAGE  [initandlisten] WiredTiger message [1576718509:151981][1:0x7fa4b031fb00], txn-recover: Main recovery loop: starting at 2/5888 to 3/256
crawlab-worker |    ...done.
crawlab-master |    ...done.
mongo_1   | 2019-12-19T01:21:49.329+0000 I  STORAGE  [initandlisten] WiredTiger message [1576718509:329342][1:0x7fa4b031fb00], txn-recover: Recovering log 2 through 3
mongo_1   | 2019-12-19T01:21:49.453+0000 I  STORAGE  [initandlisten] WiredTiger message [1576718509:453367][1:0x7fa4b031fb00], txn-recover: Recovering log 3 through 3
crawlab-worker | [GIN-debug] [WARNING] Creating an Engine instance with the Logger and Recovery middleware already attached.
crawlab-worker | 
crawlab-worker | [GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
crawlab-worker |  - using env:	export GIN_MODE=release
crawlab-worker |  - using code:	gin.SetMode(gin.ReleaseMode)
crawlab-worker | 
crawlab-worker | 2019/12/19 01:21:49  info 初始化配置成功                  
crawlab-worker | 2019/12/19 01:21:49  info 初始化日志设置成功                
crawlab-worker | 2019/12/19 01:21:49  info 默认未开启定期清理日志配置            
crawlab-master | [GIN-debug] [WARNING] Creating an Engine instance with the Logger and Recovery middleware already attached.
crawlab-master | 
crawlab-master | [GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
crawlab-master |  - using env:	export GIN_MODE=release
crawlab-master |  - using code:	gin.SetMode(gin.ReleaseMode)
crawlab-master | 
crawlab-master | 2019/12/19 01:21:49  info 初始化配置成功                  
crawlab-master | 2019/12/19 01:21:49  info 初始化日志设置成功                
crawlab-master | 2019/12/19 01:21:49  info 默认未开启定期清理日志配置            
crawlab-worker | 2019/12/19 01:21:49 error init mongodb error:no reachable servers
crawlab-worker | goroutine 1 [running]:
crawlab-worker | runtime/debug.Stack(0x0, 0x0, 0x0)
crawlab-worker | 	/usr/local/go/src/runtime/debug/stack.go:24 +0x9d
crawlab-worker | runtime/debug.PrintStack()
crawlab-worker | 	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
crawlab-worker | main.main()
crawlab-worker | 	/go/src/app/main.go:57 +0x2e0
crawlab-master | 2019/12/19 01:21:49 error init mongodb error:no reachable servers
crawlab-master | goroutine 1 [running]:
crawlab-master | runtime/debug.Stack(0x0, 0x0, 0x0)
crawlab-master | 	/usr/local/go/src/runtime/debug/stack.go:24 +0x9d
crawlab-master | runtime/debug.PrintStack()
crawlab-master | 	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
crawlab-master | main.main()
crawlab-master | 	/go/src/app/main.go:57 +0x2e0
crawlab-worker | panic: no reachable servers
crawlab-worker | 
crawlab-worker | goroutine 1 [running]:
crawlab-worker | main.main()
crawlab-worker | 	/go/src/app/main.go:58 +0x2c05
crawlab-master | panic: no reachable servers
crawlab-master | 
crawlab-master | goroutine 1 [running]:
crawlab-master | main.main()
crawlab-master | 	/go/src/app/main.go:58 +0x2c05
mongo_1   | 2019-12-19T01:21:49.531+0000 I  STORAGE  [initandlisten] WiredTiger message [1576718509:531376][1:0x7fa4b031fb00], txn-recover: Set global recovery timestamp: (0,0)
mongo_1   | 2019-12-19T01:21:49.539+0000 I  RECOVERY [initandlisten] WiredTiger recoveryTimestamp. Ts: Timestamp(0, 0)
mongo_1   | 2019-12-19T01:21:49.543+0000 I  STORAGE  [initandlisten] Timestamp monitor starting
mongo_1   | 2019-12-19T01:21:49.550+0000 I  CONTROL  [initandlisten] 
mongo_1   | 2019-12-19T01:21:49.550+0000 I  CONTROL  [initandlisten] ** WARNING: Access control is not enabled for the database.
mongo_1   | 2019-12-19T01:21:49.550+0000 I  CONTROL  [initandlisten] **          Read and write access to data and configuration is unrestricted.
mongo_1   | 2019-12-19T01:21:49.550+0000 I  CONTROL  [initandlisten] 
mongo_1   | 2019-12-19T01:21:49.553+0000 I  SHARDING [initandlisten] Marking collection local.system.replset as collection version: <unsharded>
mongo_1   | 2019-12-19T01:21:49.554+0000 I  STORAGE  [initandlisten] Flow Control is enabled on this deployment.
mongo_1   | 2019-12-19T01:21:49.554+0000 I  SHARDING [initandlisten] Marking collection admin.system.roles as collection version: <unsharded>
mongo_1   | 2019-12-19T01:21:49.555+0000 I  SHARDING [initandlisten] Marking collection admin.system.version as collection version: <unsharded>
mongo_1   | 2019-12-19T01:21:49.556+0000 I  SHARDING [initandlisten] Marking collection local.startup_log as collection version: <unsharded>
mongo_1   | 2019-12-19T01:21:49.556+0000 I  FTDC     [initandlisten] Initializing full-time diagnostic data capture with directory '/data/db/diagnostic.data'
mongo_1   | 2019-12-19T01:21:49.558+0000 I  SHARDING [LogicalSessionCacheRefresh] Marking collection config.system.sessions as collection version: <unsharded>
mongo_1   | 2019-12-19T01:21:49.559+0000 I  SHARDING [LogicalSessionCacheReap] Marking collection config.transactions as collection version: <unsharded>
mongo_1   | 2019-12-19T01:21:49.559+0000 I  NETWORK  [initandlisten] Listening on /tmp/mongodb-27017.sock

```
