### ISSUE TITLE
redis和mongodb启动正常，crawlab无法启动

### ISSUE THREAD

**Issue by zsmdata** [crawlab-team/crawlab#386]
## 首先这是我的启动命令，10.25.3.15是我的宿主机ip不是容器ip。
```
docker run -d --name crawlab \
        -e CRAWLAB_REDIS_ADDRESS=10.25.3.15:6379 \
        -e CRAWLAB_MONGO_HOST=10.25.3.15:27017 \
        -e CRAWLAB_SERVER_MASTER=Y \
        -e CRAWLAB_API_ADDRESS=http://10.25.3.15:8000 \
        -p 8080:8080 \
        -p 8000:8000 \
        -v /var/logs/crawlab:/var/logs/crawlab \
        tikazyq/crawlab:0.3.0
```

## 其次，redis和mongodb运行正常，都可以用客户端连接到。
```
# docker ps -a
CONTAINER ID        IMAGE                              COMMAND                  CREATED              STATUS                          PORTS                      NAMES
cbc9afa4dd23        tikazyq/crawlab:0.3.0              "/bin/sh /app/docker…"   About a minute ago   Exited (2) About a minute ago                              crawlab
3e699d7894f4        redis:latest                       "docker-entrypoint.s…"   7 hours ago          Up 7 hours                      0.0.0.0:6379->6379/tcp     musing_euler
1f13f0deb7b9        mongo                              "docker-entrypoint.s…"   26 hours ago         Up 26 hours                     0.0.0.0:27017->27017/tcp   mongo
```

## 这个是crawlab的报错
```
2019-12-20T09:16:04.328836179Z sed: -e expression #1, char 24: unknown option to `s'
2019-12-20T09:16:04.342651601Z  * Starting nginx nginx
2019-12-20T09:16:04.381728628Z    ...done.
2019-12-20T09:16:04.400495525Z [GIN-debug] [WARNING] Creating an Engine instance with the Logger and Recovery middleware already attached.
2019-12-20T09:16:04.400536039Z
2019-12-20T09:16:04.400540159Z [GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
2019-12-20T09:16:04.400544463Z  - using env:	export GIN_MODE=release
2019-12-20T09:16:04.400548025Z  - using code:	gin.SetMode(gin.ReleaseMode)
2019-12-20T09:16:04.400551579Z
2019-12-20T09:16:04.401112841Z 2019/12/20 09:16:04  info 初始化配置成功
2019-12-20T09:16:04.401136592Z 2019/12/20 09:16:04  info 初始化日志设置成功
2019-12-20T09:16:14.906247470Z goroutine 1 [running]:
2019-12-20T09:16:14.906288803Z runtime/debug.Stack(0x0, 0x0, 0x0)
2019-12-20T09:16:14.906297173Z 	/usr/local/go/src/runtime/debug/stack.go:24 +0x9d
2019-12-20T09:16:14.906304320Z runtime/debug.PrintStack()
2019-12-20T09:16:14.906310283Z 	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
2019-12-20T09:16:14.906315800Z main.main()
2019-12-20T09:16:14.906321270Z 	/go/src/app/main.go:33 +0x142
2019-12-20T09:16:14.908342672Z panic: no reachable servers
2019-12-20T09:16:14.908374372Z
2019-12-20T09:16:14.908385165Z goroutine 1 [running]:
2019-12-20T09:16:14.908393479Z main.main()
2019-12-20T09:16:14.908401642Z 	/go/src/app/main.go:34 +0x1cde
```
crawlab无法启动起来，加了--restart always的话，前端可以显示出来，但是点击登录就一直转圈圈。

**Comment by zsmdata** [comment]
mongodb和redis是这样启动的
docker run -d --name mongo -p 27017:27017 mongo:latest
docker run -d -p 6379:6379 -v ~/docker-demo/redis:/data redis:latest

**Comment by tikazyq** [comment]
```
docker run -d --name crawlab \
        -e CRAWLAB_REDIS_ADDRESS=10.25.3.15:6379 \
        -e CRAWLAB_MONGO_HOST=10.25.3.15 \
        -e CRAWLAB_SERVER_MASTER=Y \
        -e CRAWLAB_API_ADDRESS=http://10.25.3.15:8000 \
        -p 8080:8080 \
        -p 8000:8000 \
        -v /var/logs/crawlab:/var/logs/crawlab \
        tikazyq/crawlab:latest
```

**Comment by zsmdata** [comment]
感谢，crawlab正常了，但是向后台请求的地址是在哪里配的，前端NetWork显示的是localhost
```
Request URL: http://localhost:8000/login
```

**Comment by tikazyq** [comment]
CRAWLAB_API_ADDRESS，请删掉容器重新跑

**Comment by zsmdata** [comment]
容器删过了，重跑仍然是localhost
```
docker stop  $id && docker rm $id
```

**Comment by tikazyq** [comment]
试试用 docker-compose 来启动

**Comment by ksiailaohuyou** [comment]
感谢总算部署成功了
`docker run -d --restart always --name crawlab03 \
        -e CRAWLAB_REDIS_ADDRESS=10.2.7.61:6379 \
        -e CRAWLAB_MONGO_HOST=10.2.7.61 \
        -e CRAWLAB_SERVER_MASTER=Y \
        -e CRAWLAB_API_ADDRESS=http://10.2.7.61:8000 \
        -p 8001:8080 \
        -p 8000:8000 \
        -v /var/logs/crawlab:/var/logs/crawlab \
        tikazyq/crawlab:latest`

**Comment by ksiailaohuyou** [comment]
感谢总算部署成功了
```
docker run -d --restart always --name crawlab03 \
        -e CRAWLAB_REDIS_ADDRESS=10.2.7.61:6379 \
        -e CRAWLAB_MONGO_HOST=10.2.7.61 \
        -e CRAWLAB_SERVER_MASTER=Y \
        -e CRAWLAB_API_ADDRESS=http://10.2.7.61:8000 \
        -p 8001:8080 \
        -p 8000:8000 \
        -v /var/logs/crawlab:/var/logs/crawlab \
        tikazyq/crawlab:latest
```
