### ISSUE TITLE
docker下爬虫市场无法访问

### ISSUE THREAD

**Issue by rxrw** [crawlab-team/crawlab#893]
**Describe the bug**
使用docker启动crawlab，爬虫市场打开直接报500错误，版本0.5.1
日志信息：
```log
crawlab_1         | [GIN] 2020/12/23 - 11:38:17 | 500 |  113.136115ms |   192.168.3.237 | GET      "/repos?page_size=20&keyword=&sort_key="
crawlab_1         | goroutine 92461 [running]:
crawlab_1         | runtime/debug.Stack(0x0, 0x0, 0x0)
crawlab_1         | 	/usr/local/go/src/runtime/debug/stack.go:24 +0x9f
crawlab_1         | runtime/debug.PrintStack()
crawlab_1         | 	/usr/local/go/src/runtime/debug/stack.go:16 +0x25
crawlab_1         | crawlab/routes.GetRepoList(0xc002a7b680)
crawlab_1         | 	/go/src/app/routes/repos.go:36 +0x478
crawlab_1         | github.com/gin-gonic/gin.(*Context).Next(0xc002a7b680)
crawlab_1         | 	/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161 +0x3b
crawlab_1         | crawlab/middlewares.AuthorizationMiddleware.func1(0xc002a7b680)
crawlab_1         | 	/go/src/app/middlewares/auth.go:46 +0x1df
crawlab_1         | github.com/gin-gonic/gin.(*Context).Next(0xc002a7b680)
crawlab_1         | 	/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161 +0x3b
crawlab_1         | crawlab/middlewares.CORSMiddleware.func1(0xc002a7b680)
crawlab_1         | 	/go/src/app/middlewares/cors.go:17 +0x3a7
crawlab_1         | github.com/gin-gonic/gin.(*Context).Next(0xc002a7b680)
crawlab_1         | 	/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161 +0x3b
crawlab_1         | github.com/gin-gonic/gin.RecoveryWithWriter.func1(0xc002a7b680)
crawlab_1         | 	/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/recovery.go:83 +0x65
crawlab_1         | github.com/gin-gonic/gin.(*Context).Next(0xc002a7b680)
crawlab_1         | 	/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161 +0x3b
crawlab_1         | github.com/gin-gonic/gin.LoggerWithConfig.func1(0xc002a7b680)
crawlab_1         | 	/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/logger.go:241 +0xe5
crawlab_1         | github.com/gin-gonic/gin.(*Context).Next(0xc002a7b680)
crawlab_1         | 	/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161 +0x3b
crawlab_1         | github.com/gin-gonic/gin.(*Engine).handleHTTPRequest(0xc000034280, 0xc002a7b680)
crawlab_1         | 	/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/gin.go:409 +0x67a
crawlab_1         | github.com/gin-gonic/gin.(*Engine).ServeHTTP(0xc000034280, 0x13a0b00, 0xc001fce2a0, 0xc001e64400)
crawlab_1         | 	/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/gin.go:367 +0x14d
crawlab_1         | net/http.serverHandler.ServeHTTP(0xc000566540, 0x13a0b00, 0xc001fce2a0, 0xc001e64400)
crawlab_1         | 	/usr/local/go/src/net/http/server.go:2843 +0xa3
crawlab_1         | net/http.(*conn).serve(0xc001c58140, 0x13a6080, 0xc0002c2840)
crawlab_1         | 	/usr/local/go/src/net/http/server.go:1925 +0x8ad
crawlab_1         | created by net/http.(*Server).Serve
crawlab_1         | 	/usr/local/go/src/net/http/server.go:2969 +0x36c
```

**To Reproduce**
docker-compose.yml跟示例是一样的，直接启动

**Expected behavior**
正常展示插件市场

**Screenshots**
![image](https://user-images.githubusercontent.com/9566402/102956582-64a28600-4513-11eb-9017-be4aaf6bbd2c.png)

**Comment by tikazyq** [comment]
爬虫市场在下个版本即将废弃
