### ISSUE TITLE
spider error: forbidden

### ISSUE THREAD

**Issue by JeffreyBool** [crawlab-team/crawlab#995]
```go
 backend git:(master) ✗ go run main.go - master
Using config file: /Users/zhanggaoyuan/go/src/crawlab/backend/conf/config.yml
[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:	export GIN_MODE=release
 - using code:	gin.SetMode(gin.ReleaseMode)

spider error: forbidden
/Users/zhanggaoyuan/go/pkg/mod/github.com/crawlab-team/go-trace@v0.1.0/trace.go:11 github.com/crawlab-team/go-trace.TraceError()
/Users/zhanggaoyuan/go/pkg/mod/github.com/crawlab-team/crawlab-core@v0.6.0-beta.20210802.1344/spider/admin/service.go:190 github.com/crawlab-team/crawlab-core/spider/admin.NewSpiderAdminService()
/usr/local/Cellar/go/1.16.3/libexec/src/reflect/value.go:476 reflect.Value.call()
/usr/local/Cellar/go/1.16.3/libexec/src/reflect/value.go:337 reflect.Value.Call()
/Users/zhanggaoyuan/go/pkg/mod/go.uber.org/dig@v1.10.0/dig.go:284 go.uber.org/dig.defaultInvoker()
/Users/zhanggaoyuan/go/pkg/mod/go.uber.org/dig@v1.10.0/dig.go:710 go.uber.org/dig.(*node).Call()
/Users/zhanggaoyuan/go/pkg/mod/go.uber.org/dig@v1.10.0/param.go:245 go.uber.org/dig.paramSingle.Build()
/Users/zhanggaoyuan/go/pkg/mod/go.uber.org/dig@v1.10.0/param.go:201 go.uber.org/dig.paramList.BuildList()
/Users/zhanggaoyuan/go/pkg/mod/go.uber.org/dig@v1.10.0/dig.go:432 go.uber.org/dig.(*Container).Invoke()
/Users/zhanggaoyuan/go/pkg/mod/github.com/crawlab-team/crawlab-core@v0.6.0-beta.20210802.1344/controllers/spider.go:626 github.com/crawlab-team/crawlab-core/controllers.newSpiderContext()
/Users/zhanggaoyuan/go/pkg/mod/github.com/crawlab-team/crawlab-core@v0.6.0-beta.20210802.1344/controllers/spider.go:32 github.com/crawlab-team/crawlab-core/controllers.getSpiderActions()
/Users/zhanggaoyuan/go/pkg/mod/github.com/crawlab-team/crawlab-core@v0.6.0-beta.20210802.1344/controllers/spider.go:647 github.com/crawlab-team/crawlab-core/controllers.newSpiderController()
/Users/zhanggaoyuan/go/pkg/mod/github.com/crawlab-team/crawlab-core@v0.6.0-beta.20210802.1344/controllers/init.go:16 github.com/crawlab-team/crawlab-core/controllers.InitControllers()
/Users/zhanggaoyuan/go/src/crawlab/backend/apps/utils.go:26 crawlab/apps.initModule()
/Users/zhanggaoyuan/go/src/crawlab/backend/apps/api.go:28 crawlab/apps.(*Api).Init()
/Users/zhanggaoyuan/go/src/crawlab/backend/apps/api.go:77 crawlab/apps.NewApi()
/Users/zhanggaoyuan/go/src/crawlab/backend/apps/master.go:60 crawlab/apps.NewMaster()
/Users/zhanggaoyuan/go/src/crawlab/backend/cmd/master.go:59 crawlab/cmd.glob..func3()
/Users/zhanggaoyuan/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:856 github.com/spf13/cobra.(*Command).execute()
/Users/zhanggaoyuan/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 github.com/spf13/cobra.(*Command).ExecuteC()
/Users/zhanggaoyuan/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897 github.com/spf13/cobra.(*Command).Execute()
/Users/zhanggaoyuan/go/src/crawlab/backend/cmd/root.go:27 crawlab/cmd.Execute()
/Users/zhanggaoyuan/go/src/crawlab/backend/main.go:8 main.main()
/usr/local/Cellar/go/1.16.3/libexec/src/runtime/proc.go:225 runtime.main()
/usr/local/Cellar/go/1.16.3/libexec/src/runtime/asm_amd64.s:1371 runtime.goexit()
panic: could not build arguments for function "github.com/crawlab-team/crawlab-core/controllers".newSpiderContext.func1 (/Users/zhanggaoyuan/go/pkg/mod/github.com/crawlab-team/crawlab-core@v0.6.0-beta.20210802.1344/controllers/spider.go:626): failed to build interfaces.SpiderAdminService: received non-nil error from function "github.com/crawlab-team/crawlab-core/spider/admin".NewSpiderAdminService (/Users/zhanggaoyuan/go/pkg/mod/github.com/crawlab-team/crawlab-core@v0.6.0-beta.20210802.1344/spider/admin/service.go:159): spider error: forbidden

goroutine 1 [running]:
github.com/crawlab-team/crawlab-core/controllers.newSpiderContext(0x491a079)
	/Users/zhanggaoyuan/go/pkg/mod/github.com/crawlab-team/crawlab-core@v0.6.0-beta.20210802.1344/controllers/spider.go:635 +0x2ac
github.com/crawlab-team/crawlab-core/controllers.getSpiderActions(0xc0005907b0, 0x3, 0xc000066900)
	/Users/zhanggaoyuan/go/pkg/mod/github.com/crawlab-team/crawlab-core@v0.6.0-beta.20210802.1344/controllers/spider.go:32 +0x26
github.com/crawlab-team/crawlab-core/controllers.newSpiderController(0xc0005907b0)
	/Users/zhanggaoyuan/go/pkg/mod/github.com/crawlab-team/crawlab-core@v0.6.0-beta.20210802.1344/controllers/spider.go:647 +0x34
github.com/crawlab-team/crawlab-core/controllers.InitControllers(0x30, 0x59a95b8)
	/Users/zhanggaoyuan/go/pkg/mod/github.com/crawlab-team/crawlab-core@v0.6.0-beta.20210802.1344/controllers/init.go:16 +0xa5
crawlab/apps.initModule(0x4e08da2, 0xb, 0x4e65b30, 0x4d4a700, 0xc000389c01)
	/Users/zhanggaoyuan/go/src/crawlab/backend/apps/utils.go:26 +0x3c
crawlab/apps.(*Api).Init(0xc0002a9c20)
	/Users/zhanggaoyuan/go/src/crawlab/backend/apps/api.go:28 +0x46
crawlab/apps.NewApi(0x5029098)
	/Users/zhanggaoyuan/go/src/crawlab/backend/apps/api.go:77 +0x65
crawlab/apps.NewMaster(0xc0000d2b08, 0x1, 0x1, 0x0, 0x1)
	/Users/zhanggaoyuan/go/src/crawlab/backend/apps/master.go:60 +0x52
crawlab/cmd.glob..func3(0x56e26e0, 0xc0003f75d0, 0x1, 0x1)
	/Users/zhanggaoyuan/go/src/crawlab/backend/cmd/master.go:59 +0xe5
github.com/spf13/cobra.(*Command).execute(0x56e26e0, 0xc0003f75c0, 0x1, 0x1, 0x56e26e0, 0xc0003f75c0)
	/Users/zhanggaoyuan/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:856 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0x56e2960, 0x0, 0xffffffff, 0xc0000ae058)
	/Users/zhanggaoyuan/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/zhanggaoyuan/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
crawlab/cmd.Execute(...)
	/Users/zhanggaoyuan/go/src/crawlab/backend/cmd/root.go:27
main.main()
	/Users/zhanggaoyuan/go/src/crawlab/backend/main.go:8 +0x2e
exit status 2
```

上面是错误

**Comment by tikazyq** [comment]
删除 `~/.crawlab`

**Comment by 17186765070** [comment]
> 删除 `~/.crawlab`

这句话是什么意思，删除crawlab.exe吗

**Comment by zhouxianwei** [comment]
同问

**Comment by kuustudio** [comment]
> .crawlab

Windows环境删除后还是报
spider error: forbidden
C:/Users/K/go/pkg/mod/github.com/crawlab-team/go-trace@v0.1.0/trace.go:11 github.com/crawlab-team/go-trace.TraceError()
D:/GitHub/crawlab-core/spider/admin/service.go:192 github.com/crawlab-team/crawlab-core/spider/admin.NewSpiderAdminService()
C:/Program Files/Go/src/reflect/value.go:543 reflect.Value.call()
C:/Program Files/Go/src/reflect/value.go:339 reflect.Value.Call()
C:/Users/K/go/pkg/mod/go.uber.org/dig@v1.10.0/dig.go:284 go.uber.org/dig.defaultInvoker()
C:/Users/K/go/pkg/mod/go.uber.org/dig@v1.10.0/dig.go:710 go.uber.org/dig.(*node).Call()
C:/Users/K/go/pkg/mod/go.uber.org/dig@v1.10.0/param.go:245 go.uber.org/dig.paramSingle.Build()
C:/Users/K/go/pkg/mod/go.uber.org/dig@v1.10.0/param.go:201 go.uber.org/dig.paramList.BuildList()
C:/Users/K/go/pkg/mod/go.uber.org/dig@v1.10.0/dig.go:432 go.uber.org/dig.(*Container).Invoke()
D:/GitHub/crawlab-core/controllers/spider.go:1104 github.com/crawlab-team/crawlab-core/controllers.newSpiderContext()
D:/GitHub/crawlab-core/controllers/spider.go:38 github.com/crawlab-team/crawlab-core/controllers.getSpiderActions()
D:/GitHub/crawlab-core/controllers/spider.go:1125 github.com/crawlab-team/crawlab-core/controllers.newSpiderController()
D:/GitHub/crawlab-core/controllers/init.go:16 github.com/crawlab-team/crawlab-core/controllers.InitControllers()
D:/GitHub/crawlab/backend/apps/utils.go:26 crawlab/apps.initModule()
D:/GitHub/crawlab/backend/apps/api.go:28 crawlab/apps.(*Api).Init()
D:/GitHub/crawlab/backend/apps/api.go:77 crawlab/apps.NewApi()
D:/GitHub/crawlab/backend/cmd/api.go:18 crawlab/cmd.glob..func1()
C:/Users/K/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:856 github.com/spf13/cobra.(*Command).execute()
C:/Users/K/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 github.com/spf13/cobra.(*Command).ExecuteC()
C:/Users/K/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897 github.com/spf13/cobra.(*Command).Execute()
D:/GitHub/crawlab/backend/cmd/root.go:27 crawlab/cmd.Execute()
D:/GitHub/crawlab/backend/main.go:8 main.main()
C:/Program Files/Go/src/runtime/proc.go:255 runtime.main()
C:/Program Files/Go/src/runtime/asm_amd64.s:1581 runtime.goexit()
panic: could not build arguments for function "github.com/crawlab-team/crawlab-core/controllers".newSpiderContext.func1 (D:/GitHub/crawlab-core/controllers/spider.go:1104): failed to build interfaces.SpiderAdminService: received non-nil error from function "github.com/crawlab-team/crawlab-core/spider/admin".NewSpiderAdminService (D:/GitHub/crawlab-core/spider/admin/service.go:161): spider error: forbidden

goroutine 1 [running]:
github.com/crawlab-team/crawlab-core/controllers.newSpiderContext()
	D:/GitHub/crawlab-core/controllers/spider.go:1113 +0x195
github.com/crawlab-team/crawlab-core/controllers.getSpiderActions()
	D:/GitHub/crawlab-core/controllers/spider.go:38 +0x1d
github.com/crawlab-team/crawlab-core/controllers.newSpiderController()
	D:/GitHub/crawlab-core/controllers/spider.go:1125 +0x2b
github.com/crawlab-team/crawlab-core/controllers.InitControllers()
	D:/GitHub/crawlab-core/controllers/init.go:16 +0xb3
crawlab/apps.initModule({0x1a40a8a, 0xb}, 0x20)
	D:/GitHub/crawlab/backend/apps/utils.go:26 +0x30
crawlab/apps.(*Api).Init(0x1)
	D:/GitHub/crawlab/backend/apps/api.go:28 +0x31
crawlab/apps.NewApi()
	D:/GitHub/crawlab/backend/apps/api.go:77 +0x6f
crawlab/cmd.glob..func1(0x23f58e0, {0x1a393a5, 0x0, 0x0})
	D:/GitHub/crawlab/backend/cmd/api.go:18 +0x19
github.com/spf13/cobra.(*Command).execute(0x23f58e0, {0x245e0f8, 0x0, 0x0})
	C:/Users/K/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:856 +0x5f8
github.com/spf13/cobra.(*Command).ExecuteC(0x23f6060)
	C:/Users/K/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x3ad
github.com/spf13/cobra.(*Command).Execute(...)
	C:/Users/K/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
crawlab/cmd.Execute(...)
	D:/GitHub/crawlab/backend/cmd/root.go:27
main.main()
	D:/GitHub/crawlab/backend/main.go:8 +0x25
